defaultTargets = ["riddle-proofs"]
name = "riddle-proofs"
version = "0.0.1"

[[lean_lib]]
name = "RiddleProofs"

[[lean_exe]]
name = "riddle-proofs"
root = "Main"


[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "ennreal-arith"
path = "../ennreal"


# [[require]]
# git = "https://github.com/wvhulle/ennreal-arith"
# name = "ennreal-arith"
# rev = "main"
