defaultTargets = ["riddle-proofs"]
name = "riddle-proofs"
version = "0.0.1"

[[lean_lib]]
name = "RiddleProofs"

[[lean_exe]]
name = "riddle-proofs"
root = "Main"


[[require]]
name = "mathlib"
scope = "leanprover-community"
