name: Lean Action CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Lean dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            .lake
          key: lean-${{ runner.os }}-${{ hashFiles('lean-toolchain', 'lakefile.toml') }}
          restore-keys: |
            lean-${{ runner.os }}-
            
      
      - name: Check Lean
        uses: leanprover/lean-action@v1
        with:
          use-github-cache: false
